# Generated by Django 6.0.5 on 2026-05-27 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospitals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregnancy_status', models.CharField(choices=[('pregnant', 'Currently Pregnant'), ('planning', 'Planning Pregnancy'), ('not_now', 'Not Right Now')], default='pregnant', max_length=20)),
                ('lmp_date', models.DateField(blank=True, help_text='Last Menstrual Period date', null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('weight_kg', models.FloatField(blank=True, null=True)),
                ('height_cm', models.FloatField(blank=True, null=True)),
                ('is_first_pregnancy', models.BooleanField(default=True)),
                ('previous_pregnancies', models.IntegerField(default=0)),
                ('previous_complications', models.JSONField(blank=True, default=list)),
                ('partner_phone', models.CharField(blank=True, max_length=20)),
                ('language', models.CharField(choices=[('en', 'English'), ('sw', 'Swahili')], default='en', max_length=5)),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('audio_guidance', models.BooleanField(default=False)),
                ('large_text_mode', models.BooleanField(default=False)),
                ('onboarding_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospitals.hospital')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
