# Generated by Django 4.2.30 on 2026-05-27 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BabyGrowth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField(help_text='Week of pregnancy', unique=True)),
                ('title', models.CharField(max_length=200)),
                ('title_sw', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('description_sw', models.TextField(blank=True)),
                ('size_comparison', models.CharField(blank=True, help_text="e.g., 'A blueberry'", max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='baby_growth_images/')),
            ],
            options={
                'verbose_name_plural': 'Baby Growth Information',
                'ordering': ['week'],
            },
        ),
    ]
