# Generated by Django 4.2.30 on 2026-06-08 11:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_user_type_providerprofile'),
        ('patients', '0002_babygrowth'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='assigned_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='accounts.providerprofile'),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='height_cm',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(50.0)]),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='previous_pregnancies',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='weight_kg',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(20.0)]),
        ),
    ]
