# Generated by Django 4.2.30 on 2026-06-13 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patientprofile_assigned_provider_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ANCMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField(help_text='Target week for this ANC milestone')),
                ('title', models.CharField(max_length=200)),
                ('title_sw', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('description_sw', models.TextField()),
            ],
            options={
                'ordering': ['week'],
            },
        ),
        migrations.AddField(
            model_name='babygrowth',
            name='length_cm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='babygrowth',
            name='organ_formation',
            field=models.TextField(blank=True, help_text='Major organs forming this week'),
        ),
        migrations.AddField(
            model_name='babygrowth',
            name='size_comparison_sw',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='babygrowth',
            name='weight_g',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
