# Generated by Django 6.0 on 2026-06-30 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_patientprofile_font_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='babygrowth',
            name='baby_facts',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='babygrowth',
            name='baby_facts_sw',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='babygrowth',
            name='emoji',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='babygrowth',
            name='mother_feels',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='babygrowth',
            name='mother_feels_sw',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
