# Generated by Django 4.2.30 on 2026-06-06 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0001_initial'),
        ('accounts', '0002_user_user_type_user_is_verified_otpcode_partnerlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('patient', 'Patient'), ('partner', 'Partner'), ('provider', 'Healthcare Provider'), ('admin', 'Admin')], default='patient', max_length=10),
        ),
        migrations.CreateModel(
            name='ProviderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(choices=[('obstetrician', 'Obstetrician'), ('midwife', 'Midwife'), ('nurse', 'Nurse Practitioner')], max_length=20)),
                ('is_available', models.BooleanField(default=True)),
                ('max_workload', models.IntegerField(default=50)),
                ('current_workload', models.IntegerField(default=0)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='providers', to='hospitals.hospital')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='provider_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
