# Generated by Django 6.0 on 2026-06-25 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_user_type_providerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('patient', 'Mother'), ('partner', 'Partner'), ('provider', 'Healthcare Provider'), ('hospital_manager', 'Hospital Manager')], default='patient', max_length=20),
        ),
    ]
