# Generated by Django 4.2.30 on 2026-07-04 09:12, hand-edited to add a data
# migration ahead of the schema changes (see reassign_and_cleanup_roles).

from django.db import migrations, models


def reassign_and_cleanup_roles(apps, schema_editor):
    """Fold hospital_manager users into provider; drop partner-role users.

    Hospital Manager's remaining responsibilities move to Provider, so
    existing manager accounts become providers (an admin can attach a
    ProviderProfile with hospital/specialization afterwards via Django
    admin). Partner accounts have no clinical data of their own tied to
    the removed role, so they are deleted along with their PartnerLink
    rows as part of removing partner-linking entirely.
    """
    User = apps.get_model('accounts', 'User')
    PartnerLink = apps.get_model('accounts', 'PartnerLink')
    HospitalManagerProfile = apps.get_model('accounts', 'HospitalManagerProfile')

    User.objects.filter(user_type='hospital_manager').update(user_type='provider')
    HospitalManagerProfile.objects.all().delete()

    PartnerLink.objects.all().delete()
    User.objects.filter(user_type='partner').delete()


def noop_reverse(apps, schema_editor):
    """Data loss (deleted partner users/links) is not reversible."""


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_hospitalmanagerprofile'),
    ]

    operations = [
        migrations.RunPython(reassign_and_cleanup_roles, noop_reverse),
        migrations.RemoveField(
            model_name='partnerlink',
            name='partner',
        ),
        migrations.RemoveField(
            model_name='partnerlink',
            name='patient',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('patient', 'Mother'), ('provider', 'Healthcare Provider')], default='patient', max_length=20),
        ),
        migrations.DeleteModel(
            name='HospitalManagerProfile',
        ),
        migrations.DeleteModel(
            name='PartnerLink',
        ),
    ]
