# Generated by Django 4.2.30 on 2026-07-11 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_partner_and_hospital_manager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTPCode',
        ),
    ]
