# Generated by Django 6.0.5 on 2026-05-27 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_sw', models.CharField(blank=True, max_length=100)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(default='#FFD6D6', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_sw', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('description_sw', models.TextField(blank=True)),
                ('tip_type', models.CharField(choices=[('tip', 'Tip'), ('warning', 'Warning'), ('nutrition', 'Nutrition'), ('info', 'Info')], default='tip', max_length=20)),
                ('trimester', models.CharField(choices=[('all', 'All'), ('1', '1st'), ('2', '2nd'), ('3', '3rd')], default='all', max_length=5)),
                ('is_daily', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tips', to='tips.tipcategory')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
                ('tip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tips.tip')),
            ],
            options={
                'unique_together': {('user', 'tip')},
            },
        ),
    ]
