# Generated by Django 4.2.30 on 2026-06-08 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tip',
            name='is_ai_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tip',
            name='is_reviewed',
            field=models.BooleanField(default=False, help_text='Checked by medical professional'),
        ),
    ]
