# Generated by Django 6.0 on 2026-06-29 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0002_tip_is_ai_generated_tip_is_reviewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='tip',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Approved for mothers to see'),
        ),
    ]
