# Generated by Django 4.2.30 on 2026-07-22 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='verb',
            field=models.CharField(choices=[('chat_message', 'New chat message'), ('appointment_requested', 'Appointment requested'), ('appointment_confirmed', 'Appointment confirmed'), ('appointment_declined', 'Appointment declined'), ('appointment_time_proposed', 'Appointment new time proposed'), ('appointment_cancelled', 'Appointment cancelled'), ('chat_escalated', 'Chat escalated to provider')], max_length=30),
        ),
    ]
