# Generated by Django 4.2.30 on 2026-06-06 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ANCVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateTimeField(auto_now_add=True)),
                ('weight_kg', models.FloatField()),
                ('blood_pressure_systolic', models.IntegerField(help_text='Top number (e.g., 120)')),
                ('blood_pressure_diastolic', models.IntegerField(help_text='Bottom number (e.g., 80)')),
                ('gestational_age_weeks', models.IntegerField()),
                ('complications', models.CharField(choices=[('none', 'None'), ('hypertension', 'Pregnancy-induced Hypertension'), ('diabetes', 'Gestational Diabetes'), ('anemia', 'Anemia'), ('swelling', 'Severe Swelling'), ('other', 'Other Complication')], default='none', max_length=50)),
                ('visit_notes', models.TextField(blank=True)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anc_visits', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conducted_visits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-visit_date'],
            },
        ),
    ]
