# Generated by Django 6.0 on 2026-06-27 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ancvisit',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('unknown', 'Unknown'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], default='unknown', max_length=10),
        ),
        migrations.AddField(
            model_name='ancvisit',
            name='fetal_heart_rate_bpm',
            field=models.IntegerField(blank=True, help_text='Normal range: 110–160 bpm', null=True),
        ),
        migrations.AddField(
            model_name='ancvisit',
            name='fundal_height_cm',
            field=models.FloatField(blank=True, help_text='Symphysio-fundal height in cm', null=True),
        ),
        migrations.AddField(
            model_name='ancvisit',
            name='hemoglobin_g_dl',
            field=models.FloatField(blank=True, help_text='g/dL; <11 indicates anemia in pregnancy', null=True),
        ),
        migrations.AddField(
            model_name='ancvisit',
            name='hiv_status',
            field=models.CharField(choices=[('unknown', 'Unknown / Not tested'), ('negative', 'Negative'), ('positive', 'Positive'), ('on_treatment', 'Positive — on treatment'), ('treated', 'Treated')], default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='ancvisit',
            name='is_multiple_pregnancy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ancvisit',
            name='next_appointment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ancvisit',
            name='risk_level',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10),
        ),
        migrations.AddField(
            model_name='ancvisit',
            name='risk_level_override',
            field=models.BooleanField(default=False, help_text='Provider manually set the risk level — skip auto-calc'),
        ),
        migrations.AddField(
            model_name='ancvisit',
            name='risk_reasons',
            field=models.JSONField(blank=True, default=list, help_text='List of strings explaining why this visit was flagged'),
        ),
        migrations.AddField(
            model_name='ancvisit',
            name='symptoms',
            field=models.TextField(blank=True, help_text="Mother's complaints, danger signs, etc."),
        ),
        migrations.AddField(
            model_name='ancvisit',
            name='syphilis_status',
            field=models.CharField(choices=[('unknown', 'Unknown / Not tested'), ('negative', 'Negative'), ('positive', 'Positive'), ('on_treatment', 'Positive — on treatment'), ('treated', 'Treated')], default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='ancvisit',
            name='urine_glucose',
            field=models.CharField(choices=[('not_tested', 'Not tested'), ('negative', 'Negative'), ('trace', 'Trace'), ('1+', '1+'), ('2+', '2+'), ('3+', '3+'), ('4+', '4+')], default='not_tested', max_length=12),
        ),
        migrations.AddField(
            model_name='ancvisit',
            name='urine_protein',
            field=models.CharField(choices=[('not_tested', 'Not tested'), ('negative', 'Negative'), ('trace', 'Trace'), ('1+', '1+'), ('2+', '2+'), ('3+', '3+'), ('4+', '4+')], default='not_tested', max_length=12),
        ),
        migrations.AlterField(
            model_name='ancvisit',
            name='visit_notes',
            field=models.TextField(blank=True, help_text='Provider notes'),
        ),
    ]
