# Generated by Django 4.2.30 on 2026-07-22 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0002_ancvisit_blood_group_ancvisit_fetal_heart_rate_bpm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ancvisit',
            name='auto_risk_level',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', help_text='Server-computed risk level, always recalculated and stored even when the provider overrides it', max_length=10),
        ),
        migrations.AddField(
            model_name='ancvisit',
            name='risk_level_override_reason',
            field=models.TextField(blank=True, default='', help_text='Required explanation when risk_level_override is True'),
        ),
    ]
