# Generated by Django 4.2.30 on 2026-07-12 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VideoConsultation',
        ),
    ]
