# Generated by Django 4.2.30 on 2026-07-26 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_message_type_message_read_at_message_visit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatNudge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nudges', to='chat.chatroom')),
            ],
            options={
                'unique_together': {('room', 'sent_date')},
            },
        ),
    ]
