# Generated by Django 4.2.30 on 2026-07-10 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointment_provider_appointment_reminder_2h_sent_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('upcoming', 'Upcoming'), ('attended', 'Attended'), ('missed', 'Missed'), ('cancelled', 'Cancelled')], default='upcoming', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['requested', 'upcoming'])), fields=('provider', 'appointment_date', 'appointment_time'), name='unique_active_provider_slot'),
        ),
    ]
