# Generated by Django 4.2.30 on 2026-07-12 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_alter_auditlog_event_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SystemMaintenance',
        ),
    ]
