# Generated by Django 4.2.30 on 2026-07-26 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_delete_systemmaintenance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='event_type',
            field=models.CharField(choices=[('login', 'User Login'), ('failed_login', 'Failed Login Attempt'), ('data_change', 'Data Modification'), ('security_alert', 'Security Alert'), ('backup', 'Database Backup'), ('system_update', 'System Update'), ('scheduled_task', 'Scheduled Task Run'), ('chat_msg_delete', 'Chat Message Deletion')], max_length=20),
        ),
    ]
