# Generated by Django 6.0.5 on 2026-05-27 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MoodLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.IntegerField(choices=[(5, 'Great'), (4, 'Good'), (3, 'Okay'), (2, 'Not well'), (1, 'Bad')])),
                ('symptoms', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('weight_kg', models.FloatField(blank=True, null=True)),
                ('baby_kicks', models.IntegerField(blank=True, null=True)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mood_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-logged_at'],
            },
        ),
    ]
