# Generated by Django 4.2.30 on 2026-06-08 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracking', '0002_symptom_alter_moodlog_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptom',
            name='is_danger_sign',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='SymptomReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_notes', models.TextField(blank=True)),
                ('risk_level', models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk')], default='low', max_length=10)),
                ('clinical_recommendation', models.TextField(blank=True)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('provider_action_taken', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptom_reports', to=settings.AUTH_USER_MODEL)),
                ('symptoms', models.ManyToManyField(related_name='reports', to='tracking.symptom')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
