# Generated by Django 4.2.30 on 2026-07-12 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_conversation_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatsession',
            name='patient',
        ),
        migrations.DeleteModel(
            name='BotMessage',
        ),
        migrations.DeleteModel(
            name='ChatSession',
        ),
    ]
