# Generated by Django 4.2.30 on 2026-07-22 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_remove_chatsession_patient_delete_botmessage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('visit_summary', 'ANC Visit Summary'), ('system', 'System notice')], default='text', max_length=20),
        ),
        migrations.AddField(
            model_name='message',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender_type',
            field=models.CharField(choices=[('chatbot', 'Health Assistant'), ('mother', 'Mother'), ('provider', 'Provider'), ('system', 'System')], max_length=10),
        ),
    ]
