"""
Gemini-powered Health Assistant engine.

Every reply is generated by Google Gemini with the full conversation history,
so the assistant remembers context, mirrors the user's language (English /
Swahili / mixed), and decides on escalation contextually.

Escalation is returned through Gemini's structured-output mode (JSON schema)
so the result is reliable: the model fills in
{reply, escalate, escalation_reason} in one forced JSON object.

Fallback: when ``GEMINI_API_KEY`` is missing or the API errors, the engine
returns a friendly "service unavailable" message (no keyword bot, no fake
answers). All actual SDK plumbing lives in ``services.gemini_service`` so
this module focuses purely on chat-domain logic.

Two safety rules are enforced in code (not just via the prompt) on every
reply this module returns, regardless of which branch produced it — see
``_finalize()``: drug dosages are stripped and replaced with a safe
redirect, and an escalation reply always mentions that a nurse has been
notified and the SOS option, even when the keyword safety net (not Gemini)
is what triggered the escalation.
"""
from __future__ import annotations

import json
import logging
import re
from typing import Iterable, Optional

from django.conf import settings

from clinical.models import DANGER_SIGN_KEYWORDS
from services import gemini_service

logger = logging.getLogger(__name__)


SYSTEM_PROMPT = """You are the Mimba Yangu Health Assistant — a warm, knowledgeable AI companion for pregnant mothers in Tanzania, available 24/7.

# Role
- Provide accurate, evidence-based maternal-health information.
- Topics: nutrition, common discomforts, danger signs, antenatal-care (ANC) visits, labour preparation, newborn care, and family planning.
- Be empathetic, supportive, and non-judgmental. Speak with the warmth of a trusted aunt or experienced midwife.
- Keep replies concise: 1–4 short paragraphs unless the mother explicitly asks for detail.

# Language behaviour
- Detect the language of EACH user message: English, Swahili, or a mix.
- Reply in the same dominant language the user used. Do not force a single language.
- If the message is pure Swahili, reply in pure Swahili.
- If the message is pure English, reply in pure English.
- If the message is mixed (e.g. "Nina headache sana leo"), understand both naturally and reply in the language that best matches the message; you may mirror their natural code-switching.
- Use locally-appropriate Tanzanian phrasing.
- Translate medical terms naturally — e.g. "pre-eclampsia" usually stays; "morning sickness" → "kichefuchefu cha asubuhi"; "anaemia" → "upungufu wa damu".

# Conversation
- You receive the full conversation so far. Remember earlier symptoms and refer back to them when relevant.
- Ask short, gentle clarifying questions when symptoms are vague (severity, duration, fetal movement, etc.).
- Never restate the entire history; build on it.

# Personalisation
- A PATIENT CONTEXT block is provided above this prompt. Use it to tailor every reply:
  * Address the mother by her first name when natural (not in every sentence).
  * Anchor advice to her current pregnancy week and trimester.
  * If her last BP is elevated, weight pre-eclampsia-related questions more carefully.
  * If her risk_level is "high", treat ambiguous symptoms more conservatively.
  * Reference her hospital by name when suggesting follow-up.
- Never read the context block back at her verbatim.

# Safety & escalation
- Set `escalate=true` ONLY when the message describes a genuine medical emergency or high-risk pregnancy situation. Examples of true emergencies (non-exhaustive):
  * Severe vaginal bleeding
  * Chest pain
  * Difficulty breathing
  * Loss of consciousness or fainting
  * Severe headache with vision changes or sudden facial/hand swelling (possible pre-eclampsia)
  * Severe abdominal pain
  * Convulsions / seizures
  * No fetal movement for >12 hours after week 28
  * Suicidal thoughts or self-harm intent
  * Membrane rupture before week 37 with no labour, or with foul-smelling fluid
  * High fever (≥38.5°C) with chills
- Do NOT escalate just because the user mentions "doctor", "hospital", "help", "nurse", or "clinic". Read the full context first; many such messages are routine questions.
- When you do escalate, the reply should briefly tell the mother what to do right now (e.g. lie on left side, stay calm, ask someone to bring her to the nearest facility) and confirm a provider is being contacted.
- `escalation_reason` should be a short clinical phrase (e.g. "heavy bleeding", "possible pre-eclampsia", "suicidal ideation") — empty string when not escalating.

# Boundaries
- Never claim to be a doctor or diagnose definitively.
- Never prescribe medication doses or specific brand-name drugs.
- Never include disclaimers like "I am an AI" unless directly asked.
- If the question is wholly unrelated to maternal/child health, kindly redirect to that scope.

# Output
- ALWAYS respond as a single JSON object matching this schema EXACTLY:
  {
    "reply": "<the reply text in the mother's language>",
    "escalate": <true|false>,
    "escalation_reason": "<short clinical phrase or empty string>"
  }
- Do not include sender labels, quotation marks around `reply`, or markdown fences.
"""


# JSON Schema describing the model's required response shape. Gemini's
# response_schema understands plain JSON Schema dicts.
RESPONSE_SCHEMA = {
    "type": "object",
    "properties": {
        "reply": {"type": "string"},
        "escalate": {"type": "boolean"},
        "escalation_reason": {"type": "string"},
    },
    "required": ["reply", "escalate", "escalation_reason"],
}


# ── Public availability helpers (used by /api/chatbot/status/) ──────────────
def is_ai_available() -> bool:
    return gemini_service.is_available()


def get_active_model() -> str:
    return gemini_service.get_model()


# ── Internal helpers ────────────────────────────────────────────────────────
def _format_patient_context(patient_context: Optional[dict]) -> str:
    """Render the PATIENT CONTEXT block prepended to SYSTEM_PROMPT.

    Returns an empty string when no context was supplied so the prompt stays
    clean for non-patient callers.
    """
    if not patient_context:
        return ""
    name = patient_context.get("name") or "unknown"
    week = patient_context.get("week")
    week_str = f"{week}" if isinstance(week, int) and week > 0 else "unknown"
    risk = patient_context.get("risk") or "unknown"
    bp_sys = patient_context.get("bp_systolic") or "unknown"
    bp_dia = patient_context.get("bp_diastolic") or "unknown"
    hospital = patient_context.get("hospital") or "unknown"
    return (
        "PATIENT CONTEXT: "
        f"Name={name}, "
        f"Week={week_str}, "
        f"Risk={risk}, "
        f"Last BP={bp_sys}/{bp_dia}, "
        f"Hospital={hospital}\n\n"
    )


def _to_gemini_history(history: Iterable) -> list[dict]:
    """Convert our ``chatbot.models.Message`` rows to Gemini "contents" turns.

    - mother → role="user"
    - chatbot / provider → role="model"
    - Merge consecutive same-role messages (Gemini also dislikes A,A,A runs)
    - Ensure the first turn is a user turn (drop any leading assistant message)
    """
    turns: list[dict] = []
    for m in history:
        role = "user" if m.sender_type == "mother" else "model"
        turns.append({"role": role, "parts": [{"text": m.content}]})

    cleaned: list[dict] = []
    for t in turns:
        if cleaned and cleaned[-1]["role"] == t["role"]:
            cleaned[-1]["parts"][0]["text"] += "\n\n" + t["parts"][0]["text"]
        else:
            cleaned.append(t)

    while cleaned and cleaned[0]["role"] != "user":
        cleaned.pop(0)

    return cleaned


def _fallback(language_hint: str, *, reason: str) -> dict:
    is_sw = (language_hint or "").lower().startswith("sw")
    if is_sw:
        msg = (
            "Samahani, msaidizi wa AI hapatikani kwa muda mfupi. "
            "Tafadhali jaribu tena baada ya dakika chache, au sema "
            "\"nataka daktari\" ili kuunganishwa na mhudumu wa afya."
        )
    else:
        msg = (
            "Sorry — the AI Health Assistant is temporarily unavailable. "
            "Please try again in a moment, or say \"I need a doctor\" to be "
            "connected with a real provider."
        )
    return {"escalate": False, "reason": reason, "bot_reply": msg, "ai_available": False}


def _keyword_escalation(text: str) -> Optional[str]:
    """Rule-based safety net, independent of the Gemini call's outcome.

    Reuses the same WHO-aligned danger-sign keyword list that
    ``clinical.models.ANCVisit.evaluate_risk()`` matches against, so a
    mother describing a real emergency still gets flagged for provider
    escalation even if the AI call is slow, errors, or (for any reason)
    doesn't flag it itself.
    """
    lowered = (text or "").lower()
    for keyword in DANGER_SIGN_KEYWORDS:
        if keyword in lowered:
            return keyword
    return None


def _apply_keyword_safety_net(result: dict, keyword_hit: Optional[str]) -> dict:
    if keyword_hit and not result.get("escalate"):
        result["escalate"] = True
        result["reason"] = keyword_hit
    return result


# ── Code-level dosage filter ────────────────────────────────────────────────
# The system prompt already tells Gemini never to prescribe doses, but that's
# a request, not a guarantee. English units are numeral-first ("500mg", "2
# tablets"); Swahili idiomatically puts the noun before the numeral ("vidonge
# 2", "kidonge kimoja"), so both orders are matched. Deliberately broad: a
# false positive (redirecting a borderline reply to the provider) is the
# acceptable failure mode here, a missed dosage is not.
_DOSAGE_UNITS_EN = r'mg|ml|mcg|g|iu|tablets?|capsules?|drops?'
_DOSAGE_WORDS_SW = r'vidonge|kidonge|vipimo|matone'
_DOSAGE_PATTERN = re.compile(
    rf'\b(\d+(\.\d+)?\s*({_DOSAGE_UNITS_EN})|({_DOSAGE_WORDS_SW})\s*\d+)\b',
    re.IGNORECASE,
)

_DOSAGE_REDIRECT_EN = (
    "For medication amounts, please check with your provider directly — "
    "I'm not able to give specific doses. I can flag this for them if you'd like."
)
_DOSAGE_REDIRECT_SW = (
    "Kwa kiwango cha dawa, tafadhali wasiliana moja kwa moja na mhudumu wako wa afya — "
    "sijaruhusiwa kutoa kipimo maalum. Ninaweza kumjulisha kama ungependa."
)


def sanitize_reply(reply_text: str, language_hint: str = "en") -> str:
    """Replace any reply containing a drug-dosage pattern with a safe redirect."""
    if _DOSAGE_PATTERN.search(reply_text or ""):
        is_sw = (language_hint or "").lower().startswith("sw")
        return _DOSAGE_REDIRECT_SW if is_sw else _DOSAGE_REDIRECT_EN
    return reply_text


# ── Escalation notice guarantee ─────────────────────────────────────────────
# When escalate=True, the mother must be told a nurse/provider has been
# notified and that the SOS option exists — in code, not only via the prompt,
# so this holds even when the keyword safety net (not Gemini itself) is what
# triggered escalation and Gemini's own reply text never mentioned either.
_ESCALATION_NOTICE_EN = (
    " A nurse has been notified and will follow up with you soon. "
    "If you feel this is an emergency right now, please use the SOS button in the app."
)
_ESCALATION_NOTICE_SW = (
    " Muuguzi ameshaarifiwa na atawasiliana nawe hivi karibuni. "
    "Kama unahisi hii ni dharura sasa hivi, tafadhali tumia kitufe cha SOS kwenye programu."
)
_NOTICE_ALREADY_PRESENT_MARKERS = ("sos", "nurse", "muuguzi", "mhudumu")


def _ensure_escalation_notice(reply_text: str, language_hint: str) -> str:
    lowered = (reply_text or "").lower()
    if any(marker in lowered for marker in _NOTICE_ALREADY_PRESENT_MARKERS):
        return reply_text
    is_sw = (language_hint or "").lower().startswith("sw")
    notice = _ESCALATION_NOTICE_SW if is_sw else _ESCALATION_NOTICE_EN
    return (reply_text or "").rstrip() + notice


def _finalize(result: dict, language_hint: str) -> dict:
    """Cross-cutting safety rules applied to every reply, regardless of which
    branch (Gemini success, fallback, or keyword-forced) produced it."""
    reply = sanitize_reply(result.get("bot_reply") or "", language_hint)
    if result.get("escalate"):
        reply = _ensure_escalation_notice(reply, language_hint)
    result["bot_reply"] = reply
    return result


def _parse_structured_reply(raw_text: str) -> Optional[dict]:
    """Decode the JSON object Gemini returns. Returns None on bad payloads."""
    if not raw_text:
        return None
    try:
        data = json.loads(raw_text)
    except json.JSONDecodeError:
        # Sometimes models wrap JSON in markdown fences — strip and retry.
        stripped = raw_text.strip().strip("`")
        if stripped.lower().startswith("json"):
            stripped = stripped[4:].strip()
        try:
            data = json.loads(stripped)
        except json.JSONDecodeError:
            return None
    if not isinstance(data, dict):
        return None
    return data


# ── Public API ──────────────────────────────────────────────────────────────
def process_message(
    text: str,
    *,
    history: Iterable = (),
    language_hint: str = "en",
    patient_context: Optional[dict] = None,
) -> dict:
    """End-to-end AI pipeline for a mother's message.

    Args:
        text: The latest message from the mother.
        history: Iterable of ``chatbot.models.Message`` rows ordered
            oldest→newest, EXCLUDING the current message (which is appended
            internally).
        language_hint: Best-effort UI-language hint for the fallback path
            (the model itself detects the message language).
        patient_context: Optional dict with keys
            ``{name, week, risk, bp_systolic, bp_diastolic, hospital}``.

    Returns:
        ``{"escalate": bool, "reason": str | None, "bot_reply": str, "ai_available": bool}``
    """
    text = (text or "").strip()
    if not text:
        return _fallback(language_hint, reason="empty_message")

    # Independent of everything below: if AI is unreachable, times out, or
    # returns garbage, a mother describing a real danger sign must still be
    # escalated to her provider.
    keyword_hit = _keyword_escalation(text)

    if not gemini_service.is_available():
        result = _apply_keyword_safety_net(
            _fallback(language_hint, reason="ai_unavailable"), keyword_hit
        )
        return _finalize(result, language_hint)

    history_list = list(history or [])
    history_limit = getattr(settings, "AI_CHAT_HISTORY_LIMIT", 20)
    truncated = history_list[-history_limit:]
    gemini_history = _to_gemini_history(truncated)

    # Prepend the patient-context block to the system prompt so every turn is
    # personalised to this specific mother.
    system_instruction = _format_patient_context(patient_context) + SYSTEM_PROMPT

    model = gemini_service.get_model()
    logger.info(
        "Gemini request | model=%s history=%d/%d ctx=%s user=%r",
        model, len(truncated), len(history_list),
        bool(patient_context), text[:120],
    )

    raw_text = gemini_service.generate_text(
        prompt=text,
        system_instruction=system_instruction,
        history=gemini_history,
        response_schema=RESPONSE_SCHEMA,
        response_mime_type="application/json",
        model=model,
        max_output_tokens=1024,
    )

    if not raw_text:
        # gemini_service already logged the underlying error.
        result = _apply_keyword_safety_net(
            _fallback(language_hint, reason="ai_api_error"), keyword_hit
        )
        return _finalize(result, language_hint)

    data = _parse_structured_reply(raw_text)
    if not data or not (data.get("reply") or "").strip():
        logger.warning("Gemini returned non-JSON or empty reply: %r", raw_text[:200])
        result = _apply_keyword_safety_net(
            _fallback(language_hint, reason="ai_bad_payload"), keyword_hit
        )
        return _finalize(result, language_hint)

    reply_text = data["reply"].strip()
    escalate = bool(data.get("escalate", False))
    reason = (data.get("escalation_reason") or "").strip() or (
        "clinical" if escalate else None
    )

    logger.info(
        "Gemini reply | escalate=%s reason=%s reply=%r",
        escalate, reason, reply_text[:120],
    )

    result = _apply_keyword_safety_net({
        "escalate": escalate,
        "reason": reason,
        "bot_reply": reply_text,
        "ai_available": True,
    }, keyword_hit)
    return _finalize(result, language_hint)
