"""
Claude-powered Health Assistant engine.

Replaces the legacy keyword bot in ``chatbot_engine.py``. Every reply is
generated by Anthropic Claude with the full conversation history, so the
assistant remembers context, mirrors the user's language (English / Swahili /
mixed), and decides on escalation contextually.

Escalation is returned through Anthropic tool-use so the structured output
is reliable: the model fills in {reply, escalate, escalation_reason} in one
forced tool call.

Fallback: when ``ANTHROPIC_API_KEY`` is missing or the API errors, the
engine returns a friendly "service unavailable" message (no keyword bot,
no fake answers).
"""
from __future__ import annotations

import logging
from typing import Iterable, Optional

from django.conf import settings

logger = logging.getLogger(__name__)

try:
    from anthropic import Anthropic, APIError, APIConnectionError
    _HAS_SDK = True
except ImportError:  # pragma: no cover — only hit if requirements not installed
    _HAS_SDK = False
    Anthropic = None  # type: ignore[assignment]
    APIError = Exception  # type: ignore[assignment]
    APIConnectionError = Exception  # type: ignore[assignment]
    logger.warning("anthropic SDK not installed; Health Assistant disabled")


SYSTEM_PROMPT = """You are the Mimba Yangu Health Assistant — a warm, knowledgeable AI companion for pregnant mothers in Tanzania, available 24/7.

# Role
- Provide accurate, evidence-based maternal-health information.
- Topics: nutrition, common discomforts, danger signs, antenatal-care (ANC) visits, labour preparation, newborn care, and family planning.
- Be empathetic, supportive, and non-judgmental. Speak with the warmth of a trusted aunt or experienced midwife.
- Keep replies concise: 1–4 short paragraphs unless the mother explicitly asks for detail.

# Language behaviour
- Detect the language of EACH user message: English, Swahili, or a mix.
- Reply in the same dominant language the user used. Do not force a single language.
- If the message is pure Swahili, reply in pure Swahili.
- If the message is pure English, reply in pure English.
- If the message is mixed (e.g. "Nina headache sana leo"), understand both naturally and reply in the language that best matches the message; you may mirror their natural code-switching.
- Use locally-appropriate Tanzanian phrasing.
- Translate medical terms naturally — e.g. "pre-eclampsia" usually stays; "morning sickness" → "kichefuchefu cha asubuhi"; "anaemia" → "upungufu wa damu".

# Conversation
- You receive the full conversation so far. Remember earlier symptoms and refer back to them when relevant.
- Ask short, gentle clarifying questions when symptoms are vague (severity, duration, fetal movement, etc.).
- Never restate the entire history; build on it.

# Safety & escalation
- Set `escalate=true` ONLY when the message describes a genuine medical emergency or high-risk pregnancy situation. Examples of true emergencies (non-exhaustive):
  * Severe vaginal bleeding
  * Chest pain
  * Difficulty breathing
  * Loss of consciousness or fainting
  * Severe headache with vision changes or sudden facial/hand swelling (possible pre-eclampsia)
  * Severe abdominal pain
  * Convulsions / seizures
  * No fetal movement for >12 hours after week 28
  * Suicidal thoughts or self-harm intent
  * Membrane rupture before week 37 with no labour, or with foul-smelling fluid
  * High fever (≥38.5°C) with chills
- Do NOT escalate just because the user mentions "doctor", "hospital", "help", "nurse", or "clinic". Read the full context first; many such messages are routine questions.
- When you do escalate, the reply should briefly tell the mother what to do right now (e.g. lie on left side, stay calm, ask someone to bring her to the nearest facility) and confirm a provider is being contacted.
- `escalation_reason` should be a short clinical phrase (e.g. "heavy bleeding", "possible pre-eclampsia", "suicidal ideation") — empty string when not escalating.

# Boundaries
- Never claim to be a doctor or diagnose definitively.
- Never prescribe medication doses or specific brand-name drugs.
- Never include disclaimers like "I am an AI" unless directly asked.
- If the question is wholly unrelated to maternal/child health, kindly redirect to that scope.

# Output
- ALWAYS respond by calling the `respond_to_mother` tool. Do not produce free-form text.
"""

RESPOND_TOOL = {
    "name": "respond_to_mother",
    "description": (
        "Send a reply back to the mother and indicate whether the conversation "
        "must be escalated to a real human provider for clinical reasons."
    ),
    "input_schema": {
        "type": "object",
        "properties": {
            "reply": {
                "type": "string",
                "description": (
                    "The full message to display to the mother, written in the same "
                    "language she used. Do not include sender labels or quotation marks."
                ),
            },
            "escalate": {
                "type": "boolean",
                "description": (
                    "True ONLY when the message describes a true medical emergency or "
                    "high-risk pregnancy complication that needs immediate human care."
                ),
            },
            "escalation_reason": {
                "type": "string",
                "description": (
                    "Short clinical phrase explaining why you escalated "
                    "(e.g. 'severe vaginal bleeding'). Empty string when escalate=false."
                ),
            },
        },
        "required": ["reply", "escalate", "escalation_reason"],
    },
}


# ── Internal helpers ────────────────────────────────────────────────────────

def _client() -> Optional["Anthropic"]:
    if not _HAS_SDK:
        return None
    api_key = getattr(settings, "ANTHROPIC_API_KEY", "") or ""
    if not api_key:
        logger.warning("ANTHROPIC_API_KEY not set — chat will use unavailable-message fallback")
        return None
    return Anthropic(api_key=api_key)


def _to_anthropic_messages(history: Iterable, current_user_text: str) -> list[dict]:
    """Convert our Message rows into Anthropic chat format.

    - mother → user
    - chatbot / provider → assistant
    - Merge consecutive same-role messages (the API rejects A,A,A sequences)
    - Ensure the conversation starts with a user message
    - Append the current user message at the end
    """
    msgs: list[dict] = []
    for m in history:
        role = "user" if m.sender_type == "mother" else "assistant"
        msgs.append({"role": role, "content": m.content})

    cleaned: list[dict] = []
    for m in msgs:
        if cleaned and cleaned[-1]["role"] == m["role"]:
            cleaned[-1]["content"] = cleaned[-1]["content"] + "\n\n" + m["content"]
        else:
            cleaned.append(m)

    while cleaned and cleaned[0]["role"] != "user":
        cleaned.pop(0)

    cleaned.append({"role": "user", "content": current_user_text})
    return cleaned


def _fallback(language_hint: str, *, reason: str) -> dict:
    is_sw = (language_hint or "").lower().startswith("sw")
    if is_sw:
        msg = (
            "Samahani, msaidizi wa AI hapatikani kwa muda mfupi. "
            "Tafadhali jaribu tena baada ya dakika chache, au sema "
            "\"nataka daktari\" ili kuunganishwa na mhudumu wa afya."
        )
    else:
        msg = (
            "Sorry — the AI Health Assistant is temporarily unavailable. "
            "Please try again in a moment, or say \"I need a doctor\" to be "
            "connected with a real provider."
        )
    return {"escalate": False, "reason": reason, "bot_reply": msg, "ai_available": False}


def _extract_tool_input(response) -> Optional[dict]:
    for block in getattr(response, "content", []) or []:
        if getattr(block, "type", None) == "tool_use" and getattr(block, "name", "") == "respond_to_mother":
            return block.input
    return None


# ── Public API ──────────────────────────────────────────────────────────────

def process_message(text: str, *, history: Iterable = (), language_hint: str = "en") -> dict:
    """End-to-end AI pipeline for a mother's message.

    Args:
        text: The latest message from the mother.
        history: Iterable of ``chatbot.models.Message`` rows ordered oldest→newest,
            EXCLUDING the current message (which is appended internally).
        language_hint: Best-effort UI-language hint for the fallback path
            (the model itself detects the message language).

    Returns:
        ``{"escalate": bool, "reason": str | None, "bot_reply": str, "ai_available": bool}``
    """
    text = (text or "").strip()
    if not text:
        return _fallback(language_hint, reason="empty_message")

    client = _client()
    if client is None:
        return _fallback(language_hint, reason="ai_unavailable")

    history_list = list(history or [])
    history_limit = getattr(settings, "AI_CHAT_HISTORY_LIMIT", 20)
    truncated = history_list[-history_limit:]
    messages = _to_anthropic_messages(truncated, text)
    model = getattr(settings, "ANTHROPIC_MODEL", "claude-haiku-4-5-20251001")

    logger.info(
        "AI request | model=%s history=%d/%d user=%r",
        model, len(truncated), len(history_list), text[:120],
    )

    try:
        response = client.messages.create(
            model=model,
            max_tokens=1024,
            system=SYSTEM_PROMPT,
            tools=[RESPOND_TOOL],
            tool_choice={"type": "tool", "name": "respond_to_mother"},
            messages=messages,
        )
    except APIConnectionError as e:
        logger.error("AI connection error: %s", e)
        return _fallback(language_hint, reason="ai_connection_error")
    except APIError as e:
        logger.error("AI API error: %s", e)
        return _fallback(language_hint, reason="ai_api_error")
    except Exception as e:  # noqa: BLE001
        logger.exception("Unexpected AI error: %s", e)
        return _fallback(language_hint, reason="ai_unexpected_error")

    tool_input = _extract_tool_input(response)
    if not tool_input or not (tool_input.get("reply") or "").strip():
        logger.warning("AI returned no usable tool_use block; falling back")
        return _fallback(language_hint, reason="ai_no_tool_use")

    reply_text = tool_input["reply"].strip()
    escalate = bool(tool_input.get("escalate", False))
    reason = (tool_input.get("escalation_reason") or "").strip() or (
        "clinical" if escalate else None
    )

    logger.info(
        "AI reply | escalate=%s reason=%s usage=%s reply=%r",
        escalate, reason, getattr(response, "usage", None), reply_text[:120],
    )

    return {
        "escalate": escalate,
        "reason": reason,
        "bot_reply": reply_text,
        "ai_available": True,
    }
