# Generated by Django 4.2.30 on 2026-06-06 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name', models.CharField(max_length=200)),
                ('dosage', models.CharField(help_text='e.g., 200mg', max_length=100)),
                ('frequency', models.CharField(choices=[('1', 'Once a day'), ('2', 'Twice a day'), ('3', 'Three times a day'), ('4', 'Four times a day'), ('custom', 'Custom schedule')], max_length=10)),
                ('duration_days', models.IntegerField()),
                ('instructions', models.TextField(blank=True, help_text='e.g., Take after meals')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_prescriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MedicationReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_time', models.DateTimeField()),
                ('is_sent', models.BooleanField(default=False)),
                ('is_acknowledged', models.BooleanField(default=False, help_text='User confirmed taking medication')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('sms_status', models.CharField(blank=True, help_text="Status from Africa's Talking", max_length=50)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='medication.prescription')),
            ],
            options={
                'ordering': ['scheduled_time'],
            },
        ),
    ]
