# Generated by Django 4.2.30 on 2026-06-08 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emergency', '0002_alter_emergencylog_action_emergencycontact'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_sw', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('text_sw', models.TextField()),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='emergencylog',
            name='is_sms_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emergencylog',
            name='provider_notified',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_sos_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='emergencylog',
            name='action',
            field=models.CharField(choices=[('sos_trigger', 'One-Tap SOS Triggered'), ('call_emergency', 'Call Emergency Services'), ('call_hospital', 'Call Hospital'), ('call_partner', 'Call Partner'), ('share_location', 'Share Location')], max_length=50),
        ),
    ]
